services:
  - type: web
    name: jcc-juridio-chicala-construcoes
    env: python
    branch: main
    rootDir: .
    # CORREÇÃO CRÍTICA: O comando 'migrate' é executado no BuildCommand para aplicar 
    # as migrações no banco de dados PostgreSQL ANTES do servidor Gunicorn iniciar.
    buildCommand: pip install -r requirements.txt && python ./manage.py compilemessages && python ./manage.py collectstatic --noinput && python ./manage.py migrate --noinput
    # O Start Command agora apenas inicia o servidor Gunicorn.
    startCommand: "gunicorn jcc_site.wsgi"
    
    plan: free
    envVars:
      # Use a versão Python 3.11.5 que você especificou
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PYTHONPATH
        value: /opt/render/project/src
